services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arbius_command_center_development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:8.0.2
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  vault:
    image: 147.135.5.142:5000/pullman14/vault:4b58501
    container_name: vault
    ports:
      - "4567:3000"
    environment:
      VAULT_API_SECRET: "secret"
      VAULT_PASSWORD: "password"
    volumes:
      - vault_data:/app/data
    restart: unless-stopped
volumes:
  postgres_data:
  redis_data:
  vault_data:
